### PR TITLE
Fix node patch and KubevirtMachine addresses change

### LINKED ISSUE #18: Node update with provider ID should not block KubevirtMachine status ready
**What happened:**
Currently the node is updated with the provider ID in the kubevirtMachine reconciler
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/83c693883aa96d7e1822b8d25166cdc6ffa5fdae/controllers/kubevirtmachine_controller.go#L296
It cause to the following behavior: as long as the node is not created, the KubevirtMachine state isn't changed to READY

**What did you expect to happen:**
The Node update should not block the KubevirtMachine Ready status

**Anything else you would like to add:**
In Openshift case, it cause to deadlock situation, because of the following conditions:
1. Node can be created only if the relevant certificate is approved
2. Certificate can be approved only if the relevant KubevirtMachine state is READY

### PR DESCRIPTION
**Pull request by nirarg**
**What this PR does / why we need it**:
1. Prevent Node patch from blocking KubevirtMachine state become to ready
2. Add MachineInternalDNS Address, set it with the vm name (hostname)
3. In case IP Address on the vmi empty, don't update the Machine addresses - requeue

In **Openshift** cluster installation, the node update cause to deadlock situation, because of the following conditions:

* Node can be created only if the relevant certificate is approved
* Certificate can be approved only if the relevant KubevirtMachine state is READY

**Which issue this PR fixes**:
fixes #18

### CODE REVIEW

File: controllers/kubevirtmachine_controller.go [hunk 1]
```diff
@@ -154,7 +157,11 @@ func (r *KubevirtMachineReconciler) Reconcile(goctx gocontext.Context, req ctrl.
 	}
 
 	// Handle non-deleted machines
-	return r.reconcileNormal(machineContext)
+	result, err := r.reconcileNormal(machineContext)
+	if err != nil || machineContext.KubevirtMachine.Spec.ProviderID == nil {
+		return result, err
+	}
+	return r.patchNode(machineContext)
```
Comment (davidvossel) [inline controllers/kubevirtmachine_controller.go:164]: the checking of provider id here in this if def `if err != nil || machineContext.KubevirtMachine.Spec.ProviderID == nil` short circuits this function a bit. 

It's technically correct as the code is written today, but it's not obvious that the ProviderId is somehow related to the patchNode() function, and to not call patchNode if providerID == nil.

Can we move the providerID == nil check to the `r.patchNode` function so the logic can safely run like this.

```
	result, err := r.reconcileNormal(machineContext)
	if err != nil {
		return result, err
	}
	return r.patchNode(machineContext)

```


That said, I still feel weird about the way this logic is structured. There's a defer function that attempts to always patch the machine when the top level Reconcile function returns. Maybe we should be adding this patchNode there?

So, still with moving the check for providerID == nil into the patchNode function, something like this?

```
	// Always attempt to Patch the KubevirtMachine object and status after each reconciliation.
	defer func() {
		if err := machineContext.PatchKubevirtMachine(patchHelper); err != nil {
			machineContext.Logger.Error(err, "failed to patch KubevirtMachine")
			if rerr == nil {
				rerr = err
			}
		}

		if r.patchNode(machineContext)l err != nil {
			machineContext.Logger.Error(err, "failed to patch node")
			if rerr == nil {
				rerr = err
			}
		}
	}()
```

Comment (nirarg) [reply controllers/kubevirtmachine_controller.go:164]: Regarding the first comment:
I also added the `machineContext.KubevirtMachine.Spec.ProviderID == nil` validation, because there are cases in which the `reconcileNormal` function return in the middle without error. in this case need to return the result received from `reconcileNormal` fuction and return.
The way I have to validate this is by checking if `machineContext.KubevirtMachine.Spec.ProviderID` has valid value or not.

Regarding the second comment:
`PatchMachine` function is done in the `defer func` because this function (Reconcile) is responsible on reconciling the KubevirtMachine, therefore it no meter how it finished, need to update the KubevirtMachine with the changes.
This is not the same for `PatchNode`:
* This is done as workaround, because there is no Kubevirt cloud provider
* This update not need to happen always at the function end
* Must to remember that the relevant node might not be created yet, when this function is called
* If the Node doesn't exist, need to requeue the reconciler and try again

If the `PatchNode` name is confusing, it can be changed to `updateNode`, what do you say?

Comment (davidvossel) [reply controllers/kubevirtmachine_controller.go:164]: > Regarding the first comment:
>I also added the machineContext.KubevirtMachine.Spec.ProviderID == nil validation, because there are cases in which the reconcileNormal function return in the middle without error. in this case need to return the result received from reconcileNormal fuction and return.
>The way I have to validate this is by checking if machineContext.KubevirtMachine.Spec.ProviderID has valid value or not.


yep, i get the reasoning. It's the naming of the functions and this very specific check for ProviderID that's a little strange. 

Looking at this code, how would I understand that `machineContext.KubevirtMachine.Spec.ProviderID` and `patchNode()` are related? I wouldn't draw that conclusion easily. 

If we have all the information we need in to patch the node with a providerID early, is there a reason why we can't call the original `SetProviderID()` function earlier in the reconcileNormal loop? It seems like we can call SetProviderID the moment that the VMI instance boots.

File: pkg/kubevirt/machine.go [hunk 2]
```diff
@@ -144,26 +143,12 @@ func (m *Machine) IsBootstrapped(executor CommandExecutor) bool {
 }
 
 // SetProviderID sets the KubeVirt provider ID for this kubernetes node.
```
Comment (agradouski) [inline pkg/kubevirt/machine.go:145]: please update the comment accordingly

File: pkg/workloadcluster/workloadcluster.go [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+import (
+	"github.com/pkg/errors"
+	corev1 "k8s.io/api/core/v1"
+	"k8s.io/client-go/tools/clientcmd"
+	"sigs.k8s.io/cluster-api-provider-kubevirt/pkg/context"
+	"sigs.k8s.io/controller-runtime/pkg/client"
+)
+
+//go:generate mockgen -source=./workloadcluster.go -destination=./mock/workloadcluster_generated.go -package=mock
+type WorkloadCluster interface {
```
Comment (agradouski) [inline pkg/workloadcluster/workloadcluster.go:12]: nice refactoring

File: controllers/kubevirtmachine_controller.go (hunk 1 above)
Comment (agradouski) [reply controllers/kubevirtmachine_controller.go:164]: I agree, it seems cleaner if we patched after each reconcile loop in defer function, per previous implementation, as opposed to invoking patch function explicitly, based on a specific condition.
patching logic should be generic and should handle all conditions.

Comment (nirarg) [reply controllers/kubevirtmachine_controller.go:164]: > If we have all the information we need in to patch the node with a providerID early, is there a reason why we can't call the original SetProviderID() function earlier in the reconcileNormal loop? It seems like we can call SetProviderID the moment that the VMI instance boots.

Its true that at the moment the VMI boot is done we have all the information to generate the ProviderID, but Node of this KubevirtMachine is not created yet
Therefore I changed the original `SetProviderID()` functions to only create the provider ID (and set it on the KubevirtMachine) and moved the Node update logic to another place, which will happen later, on another reconcile loop

Comment (nirarg) [reply controllers/kubevirtmachine_controller.go]: Hi @davidvossel @agradouski ,
Please see the following new commit https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/21/commits/08b66e93b6d893b4bd6db2af8e8cbef2f17f6771
* Renamed the function to `updateNodeProviderID`
* Added another status indicating if the node updated

File: pkg/kubevirt/machine.go (hunk 2 above)
Comment (nirarg) [reply pkg/kubevirt/machine.go]: Updated, see 08b66e9

File: controllers/kubevirtmachine_controller.go [hunk 4]
```diff
@@ -263,27 +269,54 @@ func (r *KubevirtMachineReconciler) reconcileNormal(ctx *context.MachineContext)
 	// Update the condition BootstrapExecSucceededCondition
 	conditions.MarkTrue(ctx.KubevirtMachine, infrav1.BootstrapExecSucceededCondition)
 
+	ipAddress := externalMachine.Address()
+	ctx.Logger.Info(fmt.Sprintf("KubevirtMachine %s: Got ipAddress <%s>", ctx.KubevirtMachine.Name, ipAddress))
+	if ipAddress == "" {
+		ctx.Logger.Info(fmt.Sprintf("KubevirtMachine %s: Got empty ipAddress, requeue", ctx.KubevirtMachine.Name))
+		return ctrl.Result{RequeueAfter: 20 * time.Second}, nil
+	}
```
Comment (davidvossel) [inline controllers/kubevirtmachine_controller.go:277]: ah, Interesting. Maybe at some point we should consider watching VMIs for this reconcile controller.

File: controllers/kubevirtmachine_controller.go [hunk 5]
```diff
@@ -154,16 +157,19 @@ func (r *KubevirtMachineReconciler) Reconcile(goctx gocontext.Context, req ctrl.
...
 	// Handle non-deleted machines
-	return r.reconcileNormal(machineContext)
+	if result, err := r.reconcileNormal(machineContext); err != nil || !machineContext.KubevirtMachine.Status.Ready {
+		return result, err
+	}
+
+	// Update the providerID on the Node
+	// The ProviderID on the Node and the providerID on  the KubevirtMachine are used to set the NodeRef
+	// This code is needed here as long as there is no Kubevirt cloud provider setting the providerID in the node
+	return r.updateNodeProviderID(machineContext)
```
Comment (davidvossel) [inline controllers/kubevirtmachine_controller.go:167]: minor nit here.

It's slightly concerning that the `result` from reconcileNormal could be overlooked in the future. I get that the way this is written this ensures that the `reconcileNormal()` result will not try to re-enqueue anything after `Status.Ready == true`. It doesn't feel right to ignore the `result` from reconcileNormal() though.

Wouldn't something like what I have below logically be the same thing as what you have now, but not run the risk of ignoring the reconcileNormal's `result` at some point in the future?

```
if !machineContext.KubevirtMachine.Status.Ready {
    return r.reconcileNormal(machineContext)
} else {
    return r.updateNodeProviderID(machineContext)
}
```

File: controllers/kubevirtmachine_controller.go (hunk 1 above)
Comment (agradouski) [reply controllers/kubevirtmachine_controller.go]: @nirarg this looks better to me
nit: maybe `r.updateNodeProviderID(machineContext)` should also be part of `r.reconcileNormal(machineContext)` routine?

Comment (nirarg) [reply controllers/kubevirtmachine_controller.go]: It doesn't feel right to me to have it in the reconcileNormal, as this action is not related to the KubevirtMachine reconciliation
Also, reconcileNormal is done only if the KubevirtMachine is not ready, which is not the condition to updateNodeProviderID, changing the location would result also with changing the condition
What do you say?

Comment (agradouski) [reply controllers/kubevirtmachine_controller.go]: @nirarg agree

File: controllers/kubevirtmachine_controller.go (hunk 5 above)
Comment (agradouski) [reply controllers/kubevirtmachine_controller.go:167]: good suggestion, to be safe in the future

Comment (nirarg) [reply controllers/kubevirtmachine_controller.go]: Changed, please review
