### PR TITLE
Fix "should succeed with the kubevirt cluster being deleted" unit test

### LINKED ISSUE #258: Unit-Test is broken
## What steps did you take and what happened
I ran the unit tests.

The `[It] should succeed with the kubevirt cluster being deleted.` test failed with the following log:
```
------------------------------
•! [PANICKED] [0.001 seconds]
Reconcile
.../cluster-api-provider-kubevirt/controllers/kubevirtcluster_controller_test.go:37
  reconcile cluster with finalizer and deletion time stamp
  .../cluster-api-provider-kubevirt/controllers/kubevirtcluster_controller_test.go:143
    [It] should succeed with the kubevirt cluster being deleted.
    .../cluster-api-provider-kubevirt/controllers/kubevirtcluster_controller_test.go:155

  Test Panicked
  In [It] at: /usr/local/go1.20.3/src/runtime/panic.go:260

  runtime error: invalid memory address or nil pointer dereference

  Full Stack Trace
    sigs.k8s.io/cluster-api-provider-kubevirt/controllers.(*KubevirtClusterReconciler).deleteExtraGVK(0x37b3ce0, 0xc0003f26c0, {{0x2614d0d, 0x0}, {0x2614d0e, 0x2}, {0x2622de1, 0xd}})
    	.../cluster-api-provider-kubevirt/controllers/kubevirtcluster_controller.go:292 +0x323
    sigs.k8s.io/cluster-api-provider-kubevirt/controllers.(*KubevirtClusterReconciler).reconcileDelete(0x37b3ce0, 0xc0003f26c0, 0x7f94dc5b71a8?)
    	.../cluster-api-provider-kubevirt/controllers/kubevirtcluster_controller.go:255 +0x5ec
    sigs.k8s.io/cluster-api-provider-kubevirt/controllers.(*KubevirtClusterReconciler).Reconcile(0x37b3ce0, {0x28db298?, 0xc000050168}, {{{0x0?, 0x37e4790?}, {0x2631233?, 0x37e4790?}}})
    	.../cluster-api-provider-kubevirt/controllers/kubevirtcluster_controller.go:155 +0xaaa
    sigs.k8s.io/cluster-api-provider-kubevirt/controllers_test.glob..func1.5.3()
    	.../cluster-api-provider-kubevirt/controllers/kubevirtcluster_controller_test.go:168 +0x1ea
------------------------------
```

### What did you expect to happen
The test should pass

### Anything else you would like to add
The reason for this failure is that the new `KubevirtClusterReconciler.APIReader` field is not mocked on unit tests, leaving its value as `nil`. When the test triggers call to `APIReader.List()`, the tst fails with panic.

**Environment:**
Any

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by nunnatsa**
## What this PR does / why we need it

This unit test is broken. This PR fixes it by populating the `KubevirtClusterReconciler.APIReader` field in unit-test, for mocking.

In addition, this PR also fixes the `hack/kccm-flavor-gen.sh` script so it will
replace the hard coded names with the right variables.

## Which issue this PR fixes
fixes #258 

**Release notes**:
```release-note
None
```

### CODE REVIEW

File: hack/kccm-flavor-gen.sh [hunk 1]
```diff
@@ -5,6 +5,12 @@ set -x -e -o pipefail
 kccm_template=/tmp/kccm.yaml
 
 kubectl kustomize config/kccm > $kccm_template
+
+
+sed -i \
+    -E "s|(namespace: )kvcluster|\1\${NAMESPACE}|g;s|(^.*cluster-name=)kvcluster|\1\${CLUSTER_NAME}|g" \
```
Comment (qinqon) [inline hack/kccm-flavor-gen.sh:11]: Do you know if we can parameterize it at cloud-provider-kubevirt with something like https://github.com/cert-manager/cert-manager/blob/f970eca76265ff22c868dab3699cdd3cae26e90f/deploy/charts/cert-manager/templates/webhook-deployment.yaml#L68-L69

**Review by qinqon — CHANGES_REQUESTED** [review]

**Comment by agradouski** [comment]
/lgtm
thanks for fixing @nunnatsa
